Jonnitto:
  Text:
    tagName: div
    container: false
    row: row
    col: 'col-12 col-sm'

Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          Jonnitto.Text:
            - 'NodeTypes/*'
    fusion:
      autoInclude:
        Jonnitto.Text: true
